/**
 * Bundled workflow definitions
 * Generated at build time from source workflow files
 * DO NOT EDIT - This file is auto-generated by scripts/build-workflows.js
 * 
 * Found 8 workflow files:
 * - bugfix.yaml
 * - bugfix2.yaml
 * - epcc.yaml
 * - greenfield.yaml
 * - minor.yaml
 * - posts.yaml
 * - slides.yaml
 * - waterfall.yaml
 */

import bugfixYaml from '../../workflows/bugfix.yaml?raw';
import bugfix2Yaml from '../../workflows/bugfix2.yaml?raw';
import epccYaml from '../../workflows/epcc.yaml?raw';
import greenfieldYaml from '../../workflows/greenfield.yaml?raw';
import minorYaml from '../../workflows/minor.yaml?raw';
import postsYaml from '../../workflows/posts.yaml?raw';
import slidesYaml from '../../workflows/slides.yaml?raw';
import waterfallYaml from '../../workflows/waterfall.yaml?raw';

export const BUNDLED_WORKFLOWS: Record<string, string> = {
  'bugfix': bugfixYaml,
  'bugfix2': bugfix2Yaml,
  'epcc': epccYaml,
  'greenfield': greenfieldYaml,
  'minor': minorYaml,
  'posts': postsYaml,
  'slides': slidesYaml,
  'waterfall': waterfallYaml
};

export function getBundledWorkflow(name: string): string | null {
  return BUNDLED_WORKFLOWS[name] || null;
}

export function getBundledWorkflowNames(): string[] {
  return Object.keys(BUNDLED_WORKFLOWS);
}
