/**
 * Bundled workflow definitions
 * Generated at build time from source workflow files
 * DO NOT EDIT - This file is auto-generated by scripts/build-workflows.js
 *
 * Found 12 workflow files:
 * - big-bang-conversion.yaml
 * - boundary-testing.yaml
 * - bugfix.yaml
 * - business-analysis.yaml
 * - c4-analysis.yaml
 * - epcc.yaml
 * - greenfield.yaml
 * - minor.yaml
 * - posts.yaml
 * - slides.yaml
 * - tdd.yaml
 * - waterfall.yaml
 */

import big_bang_conversionYaml from '../../workflows/big-bang-conversion.yaml?raw';
import boundary_testingYaml from '../../workflows/boundary-testing.yaml?raw';
import bugfixYaml from '../../workflows/bugfix.yaml?raw';
import business_analysisYaml from '../../workflows/business-analysis.yaml?raw';
import c4_analysisYaml from '../../workflows/c4-analysis.yaml?raw';
import epccYaml from '../../workflows/epcc.yaml?raw';
import greenfieldYaml from '../../workflows/greenfield.yaml?raw';
import minorYaml from '../../workflows/minor.yaml?raw';
import postsYaml from '../../workflows/posts.yaml?raw';
import slidesYaml from '../../workflows/slides.yaml?raw';
import tddYaml from '../../workflows/tdd.yaml?raw';
import waterfallYaml from '../../workflows/waterfall.yaml?raw';

export const BUNDLED_WORKFLOWS: Record<string, string> = {
  'big-bang-conversion': big_bang_conversionYaml,
  'boundary-testing': boundary_testingYaml,
  bugfix: bugfixYaml,
  'business-analysis': business_analysisYaml,
  'c4-analysis': c4_analysisYaml,
  epcc: epccYaml,
  greenfield: greenfieldYaml,
  minor: minorYaml,
  posts: postsYaml,
  slides: slidesYaml,
  tdd: tddYaml,
  waterfall: waterfallYaml,
};

export function getBundledWorkflow(name: string): string | null {
  return BUNDLED_WORKFLOWS[name] || null;
}

export function getBundledWorkflowNames(): string[] {
  return Object.keys(BUNDLED_WORKFLOWS);
}
