/**
 * Development version of bundled workflow definitions
 * Generated from source workflow files for development mode
 * DO NOT EDIT - This file is auto-generated by scripts/build-dev-workflows.js
 * 
 * Found 8 workflow files:
 * - bugfix.yaml
 * - bugfix3.yaml
 * - epcc.yaml
 * - greenfield.yaml
 * - minor.yaml
 * - posts.yaml
 * - slides.yaml
 * - waterfall.yaml
 */

import bugfixYaml from '../../../resources/workflows/bugfix.yaml?raw';
import bugfix3Yaml from '../../../resources/workflows/bugfix3.yaml?raw';
import epccYaml from '../../../resources/workflows/epcc.yaml?raw';
import greenfieldYaml from '../../../resources/workflows/greenfield.yaml?raw';
import minorYaml from '../../../resources/workflows/minor.yaml?raw';
import postsYaml from '../../../resources/workflows/posts.yaml?raw';
import slidesYaml from '../../../resources/workflows/slides.yaml?raw';
import waterfallYaml from '../../../resources/workflows/waterfall.yaml?raw';

export const BUNDLED_WORKFLOWS: Record<string, string> = {
  'bugfix': bugfixYaml,
  'bugfix3': bugfix3Yaml,
  'epcc': epccYaml,
  'greenfield': greenfieldYaml,
  'minor': minorYaml,
  'posts': postsYaml,
  'slides': slidesYaml,
  'waterfall': waterfallYaml
};

export function getBundledWorkflow(name: string): string | null {
  return BUNDLED_WORKFLOWS[name] || null;
}

export function getBundledWorkflowNames(): string[] {
  return Object.keys(BUNDLED_WORKFLOWS);
}
