/**
 * Tests for "none" template functionality
 * 
 * Tests the ability to disable specific document types using "none" templates
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { ProjectDocsManager } from '../../src/project-docs-manager.js';
import { join } from 'path';
import { tmpdir } from 'os';
import { mkdir, rmdir } from 'fs/promises';

describe('None Template Functionality', () => {
  let testProjectPath: string;
  let projectDocsManager: ProjectDocsManager;

  beforeEach(async () => {
    // Create test project directory
    testProjectPath = join(tmpdir(), `none-template-test-${Date.now()}`);
    await mkdir(testProjectPath, { recursive: true });

    projectDocsManager = new ProjectDocsManager();
  });

  afterEach(async () => {
    // Clean up test directory
    try {
      await rmdir(testProjectPath, { recursive: true });
    } catch (error) {
      // Ignore cleanup errors
    }
  });

  describe('None Template Creation', () => {
    it('should create none template for architecture', async () => {
      const result = await projectDocsManager.createOrLinkProjectDocs(
        testProjectPath,
        {
          architecture: 'none',
          requirements: 'freestyle',
          design: 'freestyle'
        },
        {}
      );

      expect(result.created).toContain('architecture.md');
      expect(result.created).toContain('requirements.md');
      expect(result.created).toContain('design.md');

      // Verify the none template content
      const archContent = await projectDocsManager.readDocument(testProjectPath, 'architecture');
      expect(archContent).toContain('Architecture Placeholder');
      expect(archContent).toContain('DO NOT EDIT THIS FILE');
      expect(archContent).toContain('plan file');
    });

    it('should create none template for requirements', async () => {
      const result = await projectDocsManager.createOrLinkProjectDocs(
        testProjectPath,
        {
          architecture: 'freestyle',
          requirements: 'none',
          design: 'freestyle'
        },
        {}
      );

      expect(result.created).toContain('requirements.md');

      // Verify the none template content
      const reqContent = await projectDocsManager.readDocument(testProjectPath, 'requirements');
      expect(reqContent).toContain('Requirements Placeholder');
      expect(reqContent).toContain('DO NOT EDIT THIS FILE');
      expect(reqContent).toContain('plan file');
    });

    it('should create none template for design', async () => {
      const result = await projectDocsManager.createOrLinkProjectDocs(
        testProjectPath,
        {
          architecture: 'freestyle',
          requirements: 'freestyle',
          design: 'none'
        },
        {}
      );

      expect(result.created).toContain('design.md');

      // Verify the none template content
      const designContent = await projectDocsManager.readDocument(testProjectPath, 'design');
      expect(designContent).toContain('Design Placeholder');
      expect(designContent).toContain('DO NOT EDIT THIS FILE');
      expect(designContent).toContain('plan file');
    });

    it('should support mixed usage with none templates', async () => {
      // Create a test README file
      const readmePath = join(testProjectPath, 'README.md');
      await mkdir(testProjectPath, { recursive: true });
      const fs = await import('fs/promises');
      await fs.writeFile(readmePath, '# Test Project\n\nThis is a test project.');

      const result = await projectDocsManager.createOrLinkProjectDocs(
        testProjectPath,
        {
          architecture: 'freestyle',  // Template
          design: 'none'              // None template
        },
        {
          requirements: readmePath    // File link
        }
      );

      expect(result.created).toContain('architecture.md');
      expect(result.created).toContain('design.md');
      expect(result.linked).toContain('requirements.md');

      // Verify each document type
      const archContent = await projectDocsManager.readDocument(testProjectPath, 'architecture');
      expect(archContent).toContain('INSTRUCTIONS FOR ARCHITECTURE');

      const reqContent = await projectDocsManager.readDocument(testProjectPath, 'requirements');
      expect(reqContent).toContain('This is a test project');

      const designContent = await projectDocsManager.readDocument(testProjectPath, 'design');
      expect(designContent).toContain('Design Placeholder');
      expect(designContent).toContain('DO NOT EDIT THIS FILE');
    });

    it('should create all none templates when all are disabled', async () => {
      const result = await projectDocsManager.createOrLinkProjectDocs(
        testProjectPath,
        {
          architecture: 'none',
          requirements: 'none',
          design: 'none'
        },
        {}
      );

      expect(result.created).toEqual(['architecture.md', 'requirements.md', 'design.md']);
      expect(result.linked).toEqual([]);

      // Verify all contain placeholder content
      const archContent = await projectDocsManager.readDocument(testProjectPath, 'architecture');
      const reqContent = await projectDocsManager.readDocument(testProjectPath, 'requirements');
      const designContent = await projectDocsManager.readDocument(testProjectPath, 'design');

      expect(archContent).toContain('Architecture Placeholder');
      expect(reqContent).toContain('Requirements Placeholder');
      expect(designContent).toContain('Design Placeholder');

      // All should contain the DO NOT EDIT instruction
      expect(archContent).toContain('DO NOT EDIT THIS FILE');
      expect(reqContent).toContain('DO NOT EDIT THIS FILE');
      expect(designContent).toContain('DO NOT EDIT THIS FILE');
    });
  });

  describe('Template Discovery', () => {
    it('should include none in available templates', async () => {
      const availableTemplates = await projectDocsManager.templateManager.getAvailableTemplates();
      
      expect(availableTemplates.architecture).toContain('none');
      expect(availableTemplates.requirements).toContain('none');
      expect(availableTemplates.design).toContain('none');
    });
  });
});
